### ISSUE TITLE
capture and apply

### ISSUE THREAD

**Issue by wingers999** [josemesona/ManagedDism#35]
Firstly, great work on this, has proved extremely useful for my project

Can I ask if you have any plans to add the DISM functionality offered by Apply-Image and Capture-Image, so I can then use this API for my imaging program as well

Thanks

**Comment by josemesona** [comment]
You'll want to use my other library for applying and capturing images, [Wimgapi](https://github.com/josemesona/ManagedWimgApi).  DISM only manages existing images.

Here's an example on applying an image:

https://github.com/josemesona/ManagedWimgApi/wiki/Apply-an-Image

**Comment by wingers999** [comment]
Okay thanks, hadn’t seen that one – will take a further look

But DISM command line certainly does more than just manage existing images? As I use it daily to roll out images to client machines e.g.

dism /Apply-Image /ImageFile:E:\Imaging10\1-Image\Win10081117r6.wim /Index:1 /ApplyDir:W:\

Darren Rose
PC Assist @ Home

01508 471459
darren.rose@pcassistonline.co.uk<mailto:darren.rose@pcassistonline.co.uk>
www.pcassistonline.co.uk<http://www.pcassistonline.co.uk>

**Comment by josemesona** [comment]
Yeah I know its confusing.  `Dism.exe` uses `WIMGAPI` to create and apply images.  This is because `WIMGAPI` just creates images in a generic way that can contain anything.  To modify images specific to Windows (like add drivers or features) you use `DISMAPI`.  `Dism.exe` and the Dism PowerShell CmdLets both use `WIMGAPI` under the covers depending on what operation you're performing.

So I made both libraries because I needed both.

**Comment by wingers999** [comment]
Excellent – thank you for the full explanation – I really appreciate it

Darren Rose
PC Assist @ Home

01508 471459
darren.rose@pcassistonline.co.uk<mailto:darren.rose@pcassistonline.co.uk>
www.pcassistonline.co.uk<http://www.pcassistonline.co.uk>
