### ISSUE TITLE
suggestion:  add /recurse ability to  DismApi.AddDriver

### ISSUE THREAD

**Issue by wingers999** [josemesona/ManagedDism#36]
With the standard Dism /Add-Driver command you have the /recurse switch so it install all drivers in supplied folder

I believe this would be a good addition to your API, so instead of having to point directly to an .inf, I could just point to a folder and it would install all drivers found

Just a thought

**Comment by Shidell** [comment]
It's a good suggestion, and I would posit that the intent is to map as closely to the native DISM API as possible, which is why it isn't already an option.

@josemesona might be open to adding a general "utilities" or catch-all class to handle cases like this, where the functionality is DISM-related, but not mapping directly to the native API.

**Comment by josemesona** [comment]
Yeah technically I wanted to have this just be a wrapper around the original API.  I thought about making a real API that was more like a managed interface rather than a C++ interface but I don't have time to support it.

But ideally someone would develop an interface like:

```C#
using(WindowsImage image = WindowsImage.Open(@"C:\image.wim"))
{
    image.AddDriver("C:\drivers\asdf.inf");
}
```

And under the covers it would use this API to do the interop.  You could even ILMerge it so its as clean as possible.

**Comment by Shidell** [comment]
That _would_ be a nice library. It'd also be essentially merging your managed DISM and WIM libraries--or creating a library dependent on both to achieve that goal.
